version: "3.5"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
     - "13306:3306"
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

  redis:
    image: redis:6-alpine
    volumes:
      - ./data/redis:/data
    command: ["redis-server"]

  web:
    image: node:14-slim
    working_dir: /app
    depends_on:
      - db
      - redis
    volumes:
      - ./server:/app
    ports:
      - "${WEB_SERVER_EXPOSE_PORT}:80"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
    command: bash -c "npm run auto"
    links:
      - db
      - redis

